language: ruby
rvm:
  - 1.9.3

script: bundle exec rake db:migrate
script: bundle exec rake db:test:prepare
script: bundle exec rake spec
script: bundle exec rake cucumber

language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake cucumber

bundler_args: --binstubs=./bundler_stubs